apiVersion: flowcd.io/v1alpha1
kind: FlowCD
metadata:
  name: test-flowcd
spec:
  source:
    repoURL: "https://github.com/sagnik3788/FlowCD-Examples"
    branch: "main"
    path: "/manifests"
  destination:
    namespace: "default"
  deploymentStrategy:
    type: "QuickSync"
    quickSync:
      prune: false